title: Open Science UMontreal
baseURL: https://openscience.ca/
relativeURLs: true

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: "content/en"
    languageName: "English"
    permalinks:
      blog: "/blog/:year/:month/:day/:slug"
      authors: "/team/:slug"
  fr:
    contentDir: "content/fr"
    languageName: "Fran√ßais"
    permalinks:
      blog: "/blogue/:year/:month/:day/:slug"
      authors: "/equipe/:slug"

permalinks:
  tags: "/tag/:slug/"
  categories: "/category/:slug/"

menu:
  social:
    - name: "Facebook"
      url:  "#"
    - name: "Twitter"
      url:  "https://twiter.com/OSUMontreal"
    - name: "Mastodon"
      url:  "#"

social:
  facebook: "OSUMontreal"
  instagram: "OSUMontreal"
  twitter: "OSUMontreal"

imaging:
  resampleFilter: box
  quality: 100 # default is 75
  anchor: smart # default setting
  bgColor: '#ffffff' # default bg color for JPGs

enableGitInfo: true

# Taxonomies.
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
